FROM nvidia/cuda:10.0-cudnn7-runtime-ubuntu18.04

ENV PATH /opt/conda/bin:$PATH
ENV LD_LIBRARY_PATH /usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/extras/CUPTI/lib64:$LD_LIBRARY_PATH

RUN apt-get update --fix-missing && \
    apt-get install -y wget bzip2 ca-certificates curl git libgtk2.0-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install anaconda for python 3.6, through 201907
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-4.7.10-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda clean -tipsy && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

# Set timezone
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
# Set locale
ENV LANG C.UTF-8 LC_ALL=C.UTF-8

RUN conda update conda && \
    conda install python=3.6

RUN pip install --upgrade pip setuptools && \
    pip install --no-cache-dir numpy==1.18.2 Pillow==7.1.1 PyYAML==5.3.1 setuptools==46.1.3 six==1.14.0 wheel==0.34.2 && \
    pip install --no-cache-dir torch==1.4.0+cu100 torchvision==0.5.0+cu100 -f https://download.pytorch.org/whl/torch_stable.html && \
    pip install --no-cache-dir sklearn matplotlib

# Initialize workspace
RUN mkdir /workspace
WORKDIR /workspace

# Set the default command to python3
CMD ["python3"]

